### ISSUE TITLE
Implement Darwin Core establishmentMeans and degreeOfEstablishment vocabularies

### ISSUE THREAD

**Issue by nielsklazenga** [vicflora/vicflora-laravel#3]
- [dwc:establishmentMeans](https://dwc.tdwg.org/terms/#dwc:establishmentMeans): This is what we used to call (and is still more appropriately called if you ask me) 'origin status'. Vocabulary contains values" `native`, `introduced` and `uncertain` (and some others that are less relevant) for VicFlora. This is identical to what we are already using.
- [dwc:degreeOfEstablishment](https://dwc.tdwg.org/terms/#dwc:degreeOfEstablishment): vocabulary includes `established` (our `naturalised`), `cultivated` and a few values that can be used instead of our `sparsely established`.

**Comment by nielsklazenga** [comment]
## Mapping of establishment means terms

### dwc:establishmentMeans

| Current VicFlora | Darwin Core |
|---|---|
| native | native |
| introduced | introduced |
| uncertain | uncertain |

Other terms in controlled vocabulary that we do not use: 

- `nativeReintroduced`
- `introducedAssistedColonisation`
- `vagrant`

We'll add a separate field (check box) for "introduced occurrences" ("dual status")

### dwc:degreeOfEstablishment

| Current VicFlora | Darwin Core |
|---|---|
| naturalised | established |
| native | native |
| cultivated<sup>1</sup> | cultivated |
| sparsely established | casual &vert; reproducing &vert; colonising |
| naturalised | established |

<sup>1</sup> The term in the GBIF vocabulary we used is 'managed', but it had synonyms 'captive' and 'cultivated', so I used 'cultivated'. The TDWG vocabulary has all three as separate terms.

Other terms in controlled vocabulary that we do not use: 

-  `released`
- `failing`
- `introducedAssistedColonisation`
- `colonising`
- `invasive`
- `widespreadInvasive`

**Comment by DJCantrill** [comment]
Establishment Means.  It may be useful to have the term nativereintroduced available as well.  Within the specimen collection there are specimens that have been sampled from reintroductions sometime inadvertently and we may want to display these at some point.  Not really relevant to the VicFlora profiles but maybe for future functionality?
Degree of Establishment.  I like the term colonising so things could be introduced and colonising or introduced and established
We will need some explanation within VicFlora hover boxes on terms.
Not sure how these terms allow for natives that are established or establishing outside of natural range

**Comment by nielsklazenga** [comment]
@DJCantrill , I am happy to make it available, like any of the other terms, if people think they can be relevant to VicFlora or the work we do in general. Even if we do not use the term in VicFlora, it will still be in the documentation. We can have more terms than we are actually using ourselves, just to paint a complete picture.

**Comment by nielsklazenga** [comment]
> Not sure how these terms allow for natives that are established or establishing outside of natural range

I have a separate field for that. It is also on the maps, of course.

**Comment by nielsklazenga** [comment]
Resolved by https://github.com/vicflora/vicflora-worker/commit/0297e1970ee7c25452bd4e969b0e7339c4fc6fef, ec68327118e053bdba57b75bfe229840bdc28c72, https://github.com/vicflora/vicflora-vue/commit/47ee10e405238c0b5c591b11328a81237bcd5f5a
